sudo: required
services:
  - docker

before_install:
  - docker build -t bekeeeee95/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true  bekeeeee95/react-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-110522138709"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY

  secret_access_key: "$AWS_SECRET_KEY"
  # edge: true
  # skip_cleanup: true


  # // http://dockerreact-env.eba-pfwzgfrh.us-east-1.elasticbeanstalk.com/
# arn:aws:elasticbeanstalk:us-east-1:110522138709:application/docker-react
